### ISSUE TITLE
Change the timestamp

### ISSUE THREAD

**Issue by eddoff** [pkp/crossref-ojs#5]
I wish you can update the timestamp in `filter/IssueCrossrefXmlFilter.inc.php`
If I deposit directly to Crossref the format of the timestamp is consistent of 17 numbers according to this format:
YYYYMMDDHHMMssvvv
Can you please change it in OJS so that it is consistent?

Hence change
time() 
to 
date("YmdHisv")
in the code at the two rows: https://github.com/pkp/crossref-ojs/blob/64cb750b5ac6606fbf459a8eb09f9bd757b7f332/filter/IssueCrossrefXmlFilter.inc.php#L102-L103

**Comment by ktobah** [comment]
Hi @ewhanson 

The idea is that Crossref expects and uses this format (YYYYMMDDHHMMssvvv) when depositing. The OJS crossref plugin generates the timestamp as an integer in seconds, which when depositing will be compared to the old timestamp (in this format YYYYMMDDHHMMssvvv). This will always result in the new timestamp (in integer format) being less than the old one; thus, a refusal by crossref.

We are also facing this issue.

**Comment by ewhanson** [comment]
Thanks for sharing @eddoff and @ktobah. I've found explicit confirmation of this in [two](https://community.crossref.org/t/what-is-time-stamping-error-and-how-to-fix-it/932/2) [Crossref](https://community.crossref.org/t/record-not-processed-because-submitted-version-1643750256-is-less-or-equal-to-previously-submitted-version-1-403-forbidden/2469/3) forum posts as well. I'll get the timestamp generation updated based on this.

This should be updated in this repository, the standalone OPS Crossref repository, and in the `stable-3_3_0` branch of OJS and OPS.

**Comment by asmecher** [comment]
Thanks, @ewhanson -- please go ahead.

**Comment by ewhanson** [comment]
Thanks, @asmecher. Here are the PRs for all branches if you'd like a look. Otherwise I can get them merged.

- OJS `main`: pkp/crossref-ojs#12
- OPS `main`: pkp/crossref-ops#12
- OJS `stable-3_3_0`: pkp/ojs#3430
- OPS `stable-3_3_0`: pkp/ops#298

**Comment by asmecher** [comment]
Thanks, @ewhanson, I've gone head and merged them.
